# Generated by Django 3.1.5 on 2021-05-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_buystock_sellstock_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buystock',
            name='buy_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stock'),
        ),
        migrations.AlterField(
            model_name='buystock',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sellstock',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellstock',
            name='sell_inventory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.stock'),
        ),
    ]
