# Generated by Django 3.1.5 on 2021-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210508_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystock',
            name='total_invoice',
            field=models.BigIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buystock',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sellstock',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
