# Generated by Django 3.1.5 on 2021-05-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210515_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.BigIntegerField(blank=True, max_length=100, null=True),
        ),
    ]
