# Generated by Django 3.1.5 on 2021-05-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_stock_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellstock',
            name='total_invoice',
            field=models.BigIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
