# Generated by Django 3.1.5 on 2021-05-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_sellstock_total_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buystock',
            name='total_invoice',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellstock',
            name='total_invoice',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
