# Generated by Django 3.1.5 on 2021-05-18 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210518_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellstock',
            name='sell_inventory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.stock'),
        ),
    ]
