# Generated by Django 3.1.5 on 2021-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210518_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellstock',
            name='sell_inventory',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
