# Generated by Django 3.1.5 on 2021-05-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210518_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellstock',
            old_name='total_invoice',
            new_name='selling_price',
        ),
    ]
