# Generated by Django 3.1.5 on 2021-05-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_invoice',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
