# Generated by Django 3.1.5 on 2021-05-26 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_auto_20210526_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_invoice',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
