# Generated by Django 3.1.5 on 2021-05-29 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210529_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buystock',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.company'),
        ),
    ]
